apiVersion: v1
kind: Service
metadata:
  name: aes-frontend-service
spec:
  selector:
    app: aes-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-cm
data:
  VITE_BASE_URL: "http://aes-server-service.default.svc.cluster.local:8080"


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aes-frontend-deployment
  labels:
    app: aes-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aes-frontend
  template:
    metadata:
      labels:
        app: aes-frontend
    spec:
      containers:
      - name: aes-frontend
        image: aasourav/aes-meal:0.2
        volumeMounts:
          - mountPath: /usr/share/nginx/html/config
            name: config-vol
        ports:
        - containerPort: 80
        env:
          - name: VITE_BASE_URL
            value: "http://aes-server-service.default.svc.cluster.local:8080"
      volumes:
        - name: config-vol
          configMap:
            name: frontend-cm
